              spring:
              datasource:
                url: jdbc:postgresql://dpg-d1dbgs6mcj7s73fmf810-a.oregon-postgres.render.com:5432/student_db_n867
                username: alibou_user
                password: lgwyqH8a7Dddp0dhXLqHpo1vLDUd4N8t
                driver-class-name: org.postgresql.Driver
              jpa:
                hibernate:
                  ddl-auto: create
                database: postgresql
                database-platform: org.hibernate.dialect.PostgreSQLDialect
                show-sql: true
                properties:
                  hibernate:
                    format_sql: true