spring:
  datasource:
    url: jdbc:postgresql://alibou_user:lgwyqH8a7Dddp0dhXLqHpo1vLDUd4N8t@dpg-d1dbgs6mcj7s73fmf810-a.oregon-postgres.render.com/student_db_n867
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

