            name: Build & Deploy Spring App
            on: 
              push:
                branches:
                  - main

            jobs:
              build-deploy:
                name: Build and Deploy Spring Boot App
                runs-on: ubuntu-latest

                steps:
                  - name: Checkout code
                    uses: actions/checkout@v4

                  - name: Set up JDK 17
                    uses: actions/setup-java@v4
                    with:
                      distribution: 'corretto'
                      java-version: '17'

                  - name: Cache Maven dependencies
                    uses: actions/cache@v4
                    with:
                      path: ~/.m2
                      key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                      restore-keys: ${{ runner.os }}-m2

                  - name: Unit Tests
                    run: mvn -B test --file pom.xml
                  - name: Build with Maven
                    run: mvn clean package --file pom.xml -DskipTests

                  - name: Set image tag
                    id: vars
                    run: echo "tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

                  - name: Login to Docker Hub
                    uses: docker/login-action@v3
                    with:
                      username: ${{ secrets.DOCKER_HUB_USERNAME }}
                      password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN }}

                  - name: Set up Docker Buildx
                    uses: docker/setup-buildx-action@v3

                  - name: Build and Push Docker image
                    uses: docker/build-push-action@v5
                    with:
                      context: .
                      file: Dockerfile
                      push: true
                      tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:${{ steps.vars.outputs.tag }}
                      cache-from: type=gha
                      cache-to: type=gha,mode=max