name: Build & Deploy spring app
on: 
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'


jobs:

  build-deploy:
    name: Build and Deploy Spring Boot App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name : Unit Tests
        run: mvn -B test --file pom.xml
        
      - name : Build with Maven
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: set image tags
        id: vars
        run: |
          echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >>                 $GITHUB_OUTPUT

        
      - name : Build & push Docker image
        uses : docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: | 
            ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:${{ steps.vars.outputs.TIMESTAMP }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:${{ steps.vars.outputs.SHORT_SHA }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:latest
      
      - name : Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      
      - name : Push to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses : docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: | 
            ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:${{ steps.vars.outputs.TIMESTAMP }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:${{ steps.vars.outputs.SHORT_SHA }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:latest